# Replace with your LXC IPs
YOUR_LXC_IP_1
YOUR_LXC_IP_2
# etc.



[all:vars]
# Replace this with your OCI Node Headscale IP where Loki lives
loki_push_url="https://your-loki-domain.com/loki/api/v1/push"
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'